/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jefersonMesa.Reto5.view;

/**
 *
 * @author Jeferson
 */
public class PanelProducto extends javax.swing.JFrame {

    /**
     * Creates new form PanelProducto
     */
    public PanelProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        btnBorrarProducto = new javax.swing.JButton();
        btnActualizarProducto = new javax.swing.JButton();
        btnGenerarInforme = new javax.swing.JButton();
        encabezado = new javax.swing.JLabel();
        iconMisionTic = new javax.swing.JLabel();
        iconSergioArboleda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reto5: Inventario de Productos");
        setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(810, 600));
        setSize(new java.awt.Dimension(810, 600));

        background.setBackground(new java.awt.Color(255, 153, 255));
        background.setBorder(new javax.swing.border.MatteBorder(null));
        background.setMinimumSize(new java.awt.Dimension(804, 596));
        background.setName(""); // NOI18N
        background.setPreferredSize(new java.awt.Dimension(804, 596));
        background.setRequestFocusEnabled(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 11))); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel2.setText("Precio:");

        jLabel3.setText("Inventario:");

        jButton1.setText("Agregar Producto");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        background.add(panelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 470, 160));

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDatos);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 470, 310));

        btnBorrarProducto.setBackground(new java.awt.Color(204, 204, 204));
        btnBorrarProducto.setText("Borrar Producto");
        btnBorrarProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153)));
        btnBorrarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBorrarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        background.add(btnBorrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 110, 30));

        btnActualizarProducto.setText("Actualizar Producto");
        btnActualizarProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153)));
        btnActualizarProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizarProducto.setMaximumSize(new java.awt.Dimension(83, 21));
        btnActualizarProducto.setMinimumSize(new java.awt.Dimension(83, 21));
        btnActualizarProducto.setPreferredSize(new java.awt.Dimension(83, 21));
        background.add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, 140, 30));

        btnGenerarInforme.setText("Generar Informe");
        btnGenerarInforme.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153)));
        btnGenerarInforme.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerarInforme.setMaximumSize(new java.awt.Dimension(83, 21));
        btnGenerarInforme.setMinimumSize(new java.awt.Dimension(83, 21));
        btnGenerarInforme.setPreferredSize(new java.awt.Dimension(83, 21));
        background.add(btnGenerarInforme, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 130, 30));

        encabezado.setFont(new java.awt.Font("Roboto Black", 0, 20)); // NOI18N
        encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezado.setText("¡Bienvenido a la APP de inventario");
        background.add(encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 480, 40));

        iconMisionTic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconMisionTic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jefersonMesa/Reto5/images/logo_mision-tic_310x180.png"))); // NOI18N
        iconMisionTic.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iconMisionTic.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        iconMisionTic.setMaximumSize(new java.awt.Dimension(390, 200));
        iconMisionTic.setMinimumSize(new java.awt.Dimension(390, 200));
        iconMisionTic.setPreferredSize(new java.awt.Dimension(330, 180));
        background.add(iconMisionTic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, 200));

        iconSergioArboleda.setBackground(new java.awt.Color(255, 102, 255));
        iconSergioArboleda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconSergioArboleda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jefersonMesa/Reto5/images/logo-u_segio_arboleda_400x200.png"))); // NOI18N
        iconSergioArboleda.setText("jLabel1");
        iconSergioArboleda.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        iconSergioArboleda.setMaximumSize(new java.awt.Dimension(400, 200));
        iconSergioArboleda.setMinimumSize(new java.awt.Dimension(400, 200));
        background.add(iconSergioArboleda, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 280, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(826, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnBorrarProducto;
    private javax.swing.JButton btnGenerarInforme;
    private javax.swing.JLabel encabezado;
    private javax.swing.JLabel iconMisionTic;
    private javax.swing.JLabel iconSergioArboleda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
